name: audioplayers_windows
description: Windows implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 3.1.0
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_windows
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
flutter:
  plugin:
    implements: audioplayers
    platforms:
      windows:
        pluginClass: AudioplayersWindowsPlugin

dependencies:
  audioplayers_platform_interface: 
    git:
      url: 'https://github.com/RookiePlayers/audioplayers_platform_interface-5.0.1'
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

